// scripts/translate_new_keys.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dictDir = path.join(__dirname, '../src/i18n/dictionaries');

// Comprehensive native scientific translations for all 52 languages
const TRANSLATIONS = {
  es: {
    units: {
      nano: 'nano', micro: 'micro', pico: 'pico',
      nanometer: 'nanómetro', nanometers: 'nanómetros',
      micrometer: 'micrómetro', micrometers: 'micrómetros',
      picometer: 'picómetro', picometers: 'picómetros',
      millimeter: 'milímetro', millimeters: 'milímetros',
      meter: 'metro', meters: 'metros',
      nanogram: 'nanogramo', nanograms: 'nanogramos',
      microgram: 'microgramo', micrograms: 'microgramos',
      milligram: 'miligramo', milligrams: 'miligramos',
      gram: 'gramo', grams: 'gramos',
      kilogram: 'kilogramo', kilograms: 'kilogramos',
      nanofarad: 'nanofaradio', nanofarads: 'nanofaradios',
      microfarad: 'microfaradio', microfarads: 'microfaradios',
      picofarad: 'picofaradio', picofarads: 'picofaradios',
      nanomolar: 'nanomolar', micromolar: 'micromolar',
      nanosecond: 'nanosegundo', nanoseconds: 'nanosegundos',
      microsecond: 'microsegundo', microseconds: 'microsegundos',
      second: 'segundo', seconds: 'segundos',
      newton: 'newton', newtons: 'newtons',
      micronewton: 'micronewton', micronewtons: 'micronewtons',
      tesla: 'tesla', gauss: 'gauss',
    },
    convertPage: {
      h1Pattern: 'Convertidor de {from} a {to}',
      introPattern: 'Convierte {from} ({fromSymbol}) a {to} ({toSymbol}) al instante con fórmulas científicas exactas, tablas de conversión y explicaciones métricas paso a paso.',
      formulaHeading: 'Fórmula de Conversión',
      formulaDesc: 'Para convertir de {from} ({fromSymbol}) a {to} ({toSymbol}), multiplica por {factor} (o divide entre {divisor}).',
      shortcutText: 'Atajo: mueve el punto decimal tres lugares.',
      quickTableHeading: 'Tabla de Referencia Rápida',
      faqHeading: 'Preguntas Frecuentes',
      faqQ1: '¿Cuánto es 1 {from} en {to}?',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: '¿Cuánto es 1000 {from} en {to}?',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: '¿Cuánto es 2500 {from} en {to}?',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: 'Convertidores Métricos Relacionados',
    },
    siPrefixPage: {
      badge: 'Referencia Métrica',
      title: 'Guía Completa y Matriz de los 24 Prefijos del SI',
      subtitle: 'El Sistema Internacional de Unidades (SI) define 24 prefijos métricos a lo largo de 60 órdenes de magnitud, desde quecto (10⁻³⁰) hasta quetta (10³⁰).',
      thPrefix: 'Prefijo', thSymbol: 'Símbolo', thPower: 'Potencia de 10', thScale: 'Nombre de Escala', thMultiplier: 'Valor Multiplicador',
    },
    chartsPage: {
      badge: 'Referencia Imprimible',
      title: 'Tablas de Conversión de Nano a Micro',
      subtitle: 'Matrices de consulta rápida para cálculos científicos y de laboratorio de alta frecuencia.',
      thScientific: 'Notación Científica', openCalc: 'Abrir Calculadora Interactiva y Fórmula →',
    },
    errorPage: {
      badge: 'Error 404',
      title: 'Coordenada Fuera de Rango',
      desc: 'La ruta de cálculo o documentación a escala nanométrica que solicitó no existe o se ha desplazado en el continuo métrico del SI.',
      returnHome: 'Volver a la Página Principal',
      converterBtn: 'Convertidor Nano a Micro',
      physicsBtn: 'Portal de Física de Antigravedad',
    }
  },
  de: {
    units: {
      nano: 'Nano', micro: 'Mikro', pico: 'Piko',
      nanometer: 'Nanometer', nanometers: 'Nanometer',
      micrometer: 'Mikrometer', micrometers: 'Mikrometer',
      picometer: 'Pikometer', picometers: 'Pikometer',
      millimeter: 'Millimeter', millimeters: 'Millimeter',
      meter: 'Meter', meters: 'Meter',
      nanogram: 'Nanogramm', nanograms: 'Nanogramm',
      microgram: 'Mikrogramm', micrograms: 'Mikrogramm',
      milligram: 'Milligramm', milligrams: 'Milligramm',
      gram: 'Gramm', grams: 'Gramm',
      kilogram: 'Kilogramm', kilograms: 'Kilogramm',
      nanofarad: 'Nanofarad', nanofarads: 'Nanofarad',
      microfarad: 'Mikrofarad', microfarads: 'Mikrofarad',
      picofarad: 'Pikofarad', picofarads: 'Pikofarad',
      nanomolar: 'Nanomolar', micromolar: 'Mikromolar',
      nanosecond: 'Nanosekunde', nanoseconds: 'Nanosekunden',
      microsecond: 'Mikrosekunde', microseconds: 'Mikrosekunden',
      second: 'Sekunde', seconds: 'Sekunden',
      newton: 'Newton', newtons: 'Newton',
      micronewton: 'Mikronewton', micronewtons: 'Mikronewton',
      tesla: 'Tesla', gauss: 'Gauß',
    },
    convertPage: {
      h1Pattern: '{from}-zu-{to}-Umrechner',
      introPattern: 'Rechnen Sie {from} ({fromSymbol}) sofort in {to} ({toSymbol}) um mit exakten wissenschaftlichen Formeln, Umrechnungstabellen und Schritt-für-Schritt-Erklärungen.',
      formulaHeading: 'Umrechnungsformel',
      formulaDesc: 'Um von {from} ({fromSymbol}) in {to} ({toSymbol}) umzurechnen, multiplizieren Sie mit {factor} (oder dividieren Sie durch {divisor}).',
      shortcutText: 'Abkürzung: Verschieben Sie das Komma um drei Stellen.',
      quickTableHeading: 'Schnellübersichtstabelle',
      faqHeading: 'Häufig gestellte Fragen',
      faqQ1: 'Was ist 1 {from} in {to}?',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: 'Was sind 1000 {from} in {to}?',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: 'Was sind 2500 {from} in {to}?',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: 'Verwandte metrische Umrechner',
    },
    siPrefixPage: {
      badge: 'Metrische Referenz',
      title: 'Vollständiger Leitfaden und Matrix aller 24 SI-Präfixe',
      subtitle: 'Das Internationale Einheitensystem (SI) definiert 24 metrische Präfixe über 60 Größenordnungen von Quekto (10⁻³⁰) bis Quetta (10³⁰).',
      thPrefix: 'Präfix', thSymbol: 'Symbol', thPower: 'Zehnerpotenz', thScale: 'Skalenbezeichnung', thMultiplier: 'Multiplikatorwert',
    },
    chartsPage: {
      badge: 'Druckbare Referenz',
      title: 'Nano-zu-Mikro-Umrechnungstabellen',
      subtitle: 'Schnellnachschlage-Matrizen für hochfrequente wissenschaftliche und Laborberechnungen.',
      thScientific: 'Wissenschaftliche Notation', openCalc: 'Interaktiven Rechner & Formel öffnen →',
    },
    errorPage: {
      badge: '404-Fehler',
      title: 'Koordinate außerhalb des Bereichs',
      desc: 'Die angeforderte nanoskalige Berechnungs- oder Dokumentationsroute existiert nicht oder wurde im SI-Metrik-Kontinuum verschoben.',
      returnHome: 'Zur Startseite zurückkehren',
      converterBtn: 'Nano-zu-Mikro-Umrechner',
      physicsBtn: 'Antigravitations-Physik-Hub',
    }
  },
  fr: {
    units: {
      nano: 'nano', micro: 'micro', pico: 'pico',
      nanometer: 'nanomètre', nanometers: 'nanomètres',
      micrometer: 'micromètre', micrometers: 'micromètres',
      picometer: 'picomètre', picometers: 'picomètres',
      millimeter: 'millimètre', millimeters: 'millimètres',
      meter: 'mètre', meters: 'mètres',
      nanogram: 'nanogramme', nanograms: 'nanogrammes',
      microgram: 'microgramme', micrograms: 'microgrammes',
      milligram: 'milligramme', milligrams: 'milligrammes',
      gram: 'gramme', grams: 'grammes',
      kilogram: 'kilogramme', kilograms: 'kilogrammes',
      nanofarad: 'nanofarad', nanofarads: 'nanofarads',
      microfarad: 'microfarad', microfarads: 'microfarads',
      picofarad: 'picofarad', picofarads: 'picofarads',
      nanomolar: 'nanomolaire', micromolar: 'micromolaire',
      nanosecond: 'nanoseconde', nanoseconds: 'nanosecondes',
      microsecond: 'microseconde', microseconds: 'microsecondes',
      second: 'seconde', seconds: 'secondes',
      newton: 'newton', newtons: 'newtons',
      micronewton: 'micronewton', micronewtons: 'micronewtons',
      tesla: 'tesla', gauss: 'gauss',
    },
    convertPage: {
      h1Pattern: 'Convertisseur {from} en {to}',
      introPattern: 'Convertissez instantanément {from} ({fromSymbol}) en {to} ({toSymbol}) avec des formules scientifiques exactes, des tableaux de conversion et des explications étape par étape.',
      formulaHeading: 'Formule de Conversion',
      formulaDesc: 'Pour convertir {from} ({fromSymbol}) en {to} ({toSymbol}), multipliez par {factor} (ou divisez par {divisor}).',
      shortcutText: 'Raccourci : déplacez la virgule de trois rangs.',
      quickTableHeading: 'Tableau de Référence Rapide',
      faqHeading: 'Foire Aux Questions',
      faqQ1: 'Combien vaut 1 {from} en {to} ?',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: 'Combien valent 1000 {from} en {to} ?',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: 'Combien valent 2500 {from} en {to} ?',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: 'Convertisseurs métriques associés',
    },
    siPrefixPage: {
      badge: 'Référence Métrique',
      title: 'Guide complet et matrice des 24 préfixes SI',
      subtitle: 'Le Système international d\'unités (SI) définit 24 préfixes métriques couvrant 60 ordres de grandeur, de quecto (10⁻³⁰) à quetta (10³⁰).',
      thPrefix: 'Préfixe', thSymbol: 'Symbole', thPower: 'Puissance de 10', thScale: 'Nom de l\'échelle', thMultiplier: 'Valeur multiplicatrice',
    },
    chartsPage: {
      badge: 'Référence Imprimable',
      title: 'Tableaux de Conversion Nano en Micro',
      subtitle: 'Matrices de consultation rapide pour les calculs scientifiques et de laboratoire à haute fréquence.',
      thScientific: 'Notation Scientifique', openCalc: 'Ouvrir la Calculatrice Interactive & Formule →',
    },
    errorPage: {
      badge: 'Erreur 404',
      title: 'Coordonnée hors de portée',
      desc: 'L\'itinéraire de calcul ou de documentation à l\'échelle nanométrique demandé n\'existe pas ou a été déplacé dans le continuum métrique du SI.',
      returnHome: 'Retour à l\'Accueil',
      converterBtn: 'Convertisseur Nano en Micro',
      physicsBtn: 'Centre de Recherche en Antigravité',
    }
  },
  ur: {
    units: {
      nano: 'نینو', micro: 'مائیکرو', pico: 'پیکو',
      nanometer: 'نینو میٹر', nanometers: 'نینو میٹرز',
      micrometer: 'مائیکرو میٹر', micrometers: 'مائیکرو میٹرز',
      picometer: 'پیکو میٹر', picometers: 'پیکو میٹرز',
      millimeter: 'ملی میٹر', millimeters: 'ملی میٹرز',
      meter: 'میٹر', meters: 'میٹرز',
      nanogram: 'نینو گرام', nanograms: 'نینو گرامز',
      microgram: 'مائیکرو گرام', micrograms: 'مائیکرو گرامز',
      milligram: 'ملی گرام', milligrams: 'ملی گرامز',
      gram: 'گرام', grams: 'گرامز',
      kilogram: 'کلوگرام', kilograms: 'کلوگرامز',
      nanofarad: 'نینو فیراڈ', nanofarads: 'نینو فیراڈز',
      microfarad: 'مائیکرو فیراڈ', microfarads: 'مائیکرو فیراڈز',
      picofarad: 'پیکو فیراڈ', picofarads: 'پیکو فیراڈز',
      nanomolar: 'نینو مولر', micromolar: 'مائیکرو مولر',
      nanosecond: 'نینو سیکنڈ', nanoseconds: 'نینو سیکنڈز',
      microsecond: 'مائیکرو سیکنڈ', microseconds: 'مائیکرو سیکنڈز',
      second: 'سیکنڈ', seconds: 'سیکنڈز',
      newton: 'نیوٹن', newtons: 'نیوٹنز',
      micronewton: 'مائیکرو نیوٹن', micronewtons: 'مائیکرو نیوٹنز',
      tesla: 'ٹیسلا', gauss: 'گاس',
    },
    convertPage: {
      h1Pattern: '{from} سے {to} کنورٹر',
      introPattern: '{from} ({fromSymbol}) کو فوری طور پر {to} ({toSymbol}) میں تبدیل کریں، درست سائنسی فارمولوں، کنورژن ٹیبلز اور میٹرک وضاحت کے ساتھ۔',
      formulaHeading: 'تبدیلی کا فارمولا',
      formulaDesc: '{from} ({fromSymbol}) کو {to} ({toSymbol}) میں تبدیل کرنے کے لیے {factor} سے ضرب دیں (یا {divisor} سے تقسیم کریں)۔',
      shortcutText: 'شارٹ کٹ: اعشاریہ کو تین درجے منتقل کریں۔',
      quickTableHeading: 'فوری حوالہ جدول',
      faqHeading: 'اکثر پوچھے گئے سوالات',
      faqQ1: '1 {from} میں کتنے {to} ہوتے ہیں؟',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: '1000 {from} میں کتنے {to} ہوتے ہیں؟',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: '2500 {from} میں کتنے {to} ہوتے ہیں؟',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: 'متعلقہ میٹرک کنورٹرز',
    },
    siPrefixPage: {
      badge: 'میٹرک حوالہ',
      title: 'تمام 24 SI سابقوں کی جامع گائیڈ اور میٹرکس',
      subtitle: 'انٹرنیشنل سسٹم آف یونٹس (SI) 60 آرڈرز آف میگنیٹیوڈ میں 24 میٹرک سابقوں کی وضاحت کرتا ہے، کوئیکٹو (10⁻³⁰) سے کوئٹا (10³⁰) تک۔',
      thPrefix: 'سابقہ (Prefix)', thSymbol: 'علامت', thPower: '10 کی طاقت', thScale: 'پیمانے کا نام', thMultiplier: 'ضرب کی قدر',
    },
    chartsPage: {
      badge: 'پرنٹ کے قابل حوالہ',
      title: 'نینو سے مائیکرو کنورژن چارٹس',
      subtitle: 'سائنسی اور لیبارٹری پیمائش کے لیے فوری حوالہ جاتی چارٹس۔',
      thScientific: 'سائنسی نوٹیشن', openCalc: 'انٹرایکٹو کیلکولیٹر اور فارمولا کھولیں ←',
    },
    errorPage: {
      badge: '404 خرابی',
      title: 'کوآرڈینیٹ حد سے باہر ہے',
      desc: 'آپ کا مطلوبہ نینو اسکیل حساب یا دستاویز کا صفحہ موجود نہیں ہے یا SI میٹرک تسلسل میں منتقل ہو گیا ہے۔',
      returnHome: 'مرکزی صفحہ پر واپس جائیں',
      converterBtn: 'نینو سے مائیکرو کنورٹر',
      physicsBtn: 'اینٹی گریویٹی فزکس ہب',
    }
  },
  ar: {
    units: {
      nano: 'نانو', micro: 'مايكرو', pico: 'بيكو',
      nanometer: 'نانومتر', nanometers: 'نانومترات',
      micrometer: 'مايكرومتر', micrometers: 'مايكرومترات',
      picometer: 'بيكومتر', picometers: 'بيكومترات',
      millimeter: 'ملمتر', millimeters: 'ملمترات',
      meter: 'متر', meters: 'أمتار',
      nanogram: 'نانوغرام', nanograms: 'نانوغرامات',
      microgram: 'مايكروغرام', micrograms: 'مايكروغرامات',
      milligram: 'ملغرام', milligrams: 'ملغرامات',
      gram: 'غرام', grams: 'غرامات',
      kilogram: 'كيلوغرام', kilograms: 'كيلوغرامات',
      nanofarad: 'نانوفاراد', nanofarads: 'نانوفاراد',
      microfarad: 'مايكروفاراد', microfarads: 'مايكروفاراد',
      picofarad: 'بيكوفاراد', picofarads: 'بيكوفاراد',
      nanomolar: 'نانومولار', micromolar: 'مايكرومولار',
      nanosecond: 'نانوثانية', nanoseconds: 'نانوثواني',
      microsecond: 'مايكروثانية', microseconds: 'مايكروثواني',
      second: 'ثانية', seconds: 'ثواني',
      newton: 'نيوتن', newtons: 'نيوتن',
      micronewton: 'مايكرونيوتن', micronewtons: 'مايكرونيوتن',
      tesla: 'تسلا', gauss: 'غاوس',
    },
    convertPage: {
      h1Pattern: 'محول {from} إلى {to}',
      introPattern: 'قم بتحويل {from} ({fromSymbol}) إلى {to} ({toSymbol}) على الفور باستخدام الصيغ العلمية الدقيقة وجداول التحويل والشروحات المترية خطوة بخطوة.',
      formulaHeading: 'صيغة التحويل',
      formulaDesc: 'للتحويل من {from} ({fromSymbol}) إلى {to} ({toSymbol})، اضرب في {factor} (أو اقسم على {divisor}).',
      shortcutText: 'اختصار: انقل الفاصلة العشرية ثلاث خانات.',
      quickTableHeading: 'جدول المرجع السريع',
      faqHeading: 'الأسئلة الشائعة',
      faqQ1: 'كم يساوي 1 {from} في {to}؟',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: 'كم يساوي 1000 {from} في {to}؟',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: 'كم يساوي 2500 {from} في {to}؟',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: 'محولات مترية ذات صلة',
    },
    siPrefixPage: {
      badge: 'مرجع متري',
      title: 'دليل ومصفوفة بادئات النظام الدولي (SI) الـ 24 الكاملة',
      subtitle: 'يحدد النظام الدولي للوحدات (SI) 24 بادئة مترية تمتد عبر 60 رتبة مقدارية من كويكتو (10⁻³⁰) إلى كويتا (10³⁰).',
      thPrefix: 'البادئة', thSymbol: 'الرمز', thPower: 'قوة 10', thScale: 'اسم المقياس', thMultiplier: 'قيمة المضاعف',
    },
    chartsPage: {
      badge: 'مرجع قابل للطباعة',
      title: 'جداول تحويل النانو إلى مايكرو',
      subtitle: 'مصفوفات مرجعية سريعة للحسابات العلمية والمخبرية عالية التردد.',
      thScientific: 'الترميز العلمي', openCalc: 'افتح الحاسبة التفاعلية والصيغة ←',
    },
    errorPage: {
      badge: 'خطأ 404',
      title: 'الإحداثي خارج النطاق',
      desc: 'مسار الحساب أو التوثيق النانوي المطلوب غير موجود أو تم نقله في التسلسل المتري للنظام الدولي.',
      returnHome: 'العودة إلى الصفحة الرئيسية',
      converterBtn: 'محول النانو إلى مايكرو',
      physicsBtn: 'مركز أبحاث فيزياء مضاد الجاذبية',
    }
  },
  ja: {
    units: {
      nano: 'ナノ', micro: 'マイクロ', pico: 'ピコ',
      nanometer: 'ナノメートル', nanometers: 'ナノメートル',
      micrometer: 'マイクロメートル', micrometers: 'マイクロメートル',
      picometer: 'ピコメートル', picometers: 'ピコメートル',
      millimeter: 'ミリメートル', millimeters: 'ミリメートル',
      meter: 'メートル', meters: 'メートル',
      nanogram: 'ナノグラム', nanograms: 'ナノグラム',
      microgram: 'マイクログラム', micrograms: 'マイクログラム',
      milligram: 'ミリグラム', milligrams: 'ミリグラム',
      gram: 'グラム', grams: 'グラム',
      kilogram: 'キログラム', kilograms: 'キログラム',
      nanofarad: 'ナノファラド', nanofarads: 'ナノファラド',
      microfarad: 'マイクロファラド', microfarads: 'マイクロファラド',
      picofarad: 'ピコファラド', picofarads: 'ピコファラド',
      nanomolar: 'ナノモラー', micromolar: 'マイクロモラー',
      nanosecond: 'ナノ秒', nanoseconds: 'ナノ秒',
      microsecond: 'マイクロ秒', microseconds: 'マイクロ秒',
      second: '秒', seconds: '秒',
      newton: 'ニュートン', newtons: 'ニュートン',
      micronewton: 'マイクロニュートン', micronewtons: 'マイクロニュートン',
      tesla: 'テスラ', gauss: 'ガウス',
    },
    convertPage: {
      h1Pattern: '{from}から{to}への変換ツール',
      introPattern: '{from}（{fromSymbol}）を{to}（{toSymbol}）へ瞬時に変換。正確な科学的計算式、換算表、段階的なメートル法の解説を掲載しています。',
      formulaHeading: '変換計算式',
      formulaDesc: '{from}（{fromSymbol}）から{to}（{toSymbol}）に変換するには、{factor}を掛けるか（または{divisor}で割る）。',
      shortcutText: 'ショートカット：小数点を3桁移動します。',
      quickTableHeading: 'クイック換算表',
      faqHeading: 'よくある質問',
      faqQ1: '1 {from} は何 {to} ですか？',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: '1000 {from} は何 {to} ですか？',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: '2500 {from} は何 {to} ですか？',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: '関連するメートル法変換ツール',
    },
    siPrefixPage: {
      badge: '単位系リファレンス',
      title: '全24種 SI接頭語完全ガイド＆マトリックス',
      subtitle: '国際単位系（SI）はクエクト（10⁻³⁰）からクエタ（10³⁰）まで、60桁に及ぶ24種類の接頭語を規定しています。',
      thPrefix: '接頭語', thSymbol: '記号', thPower: '10の累乗', thScale: 'スケール名', thMultiplier: '倍率値',
    },
    chartsPage: {
      badge: '印刷用リファレンス',
      title: 'ナノからマイクロへの換算チャート',
      subtitle: '高頻度の科学計算および実験室測定のためのクイックルックアップ表。',
      thScientific: '指数表記', openCalc: 'インタラクティブ計算ツールと公式を開く →',
    },
    errorPage: {
      badge: '404 エラー',
      title: '指定された座標が見つかりません',
      desc: 'リクエストされたナノスケールの計算またはドキュメントルートは存在しないか、SI連続体上で移動しました。',
      returnHome: 'ホームページに戻る',
      converterBtn: 'ナノからマイクロ変換ツール',
      physicsBtn: '反重力物理学リサーチハブ',
    }
  },
  'zh-CN': {
    units: {
      nano: '纳', micro: '微', pico: '皮',
      nanometer: '纳米', nanometers: '纳米',
      micrometer: '微米', micrometers: '微米',
      picometer: '皮米', picometers: '皮米',
      millimeter: '毫米', millimeters: '毫米',
      meter: '米', meters: '米',
      nanogram: '纳克', nanograms: '纳克',
      microgram: '微克', micrograms: '微克',
      milligram: '毫克', milligrams: '毫克',
      gram: '克', grams: '克',
      kilogram: '千克', kilograms: '千克',
      nanofarad: '纳法', nanofarads: '纳法',
      microfarad: '微法', microfarads: '微法',
      picofarad: '皮法', picofarads: '皮法',
      nanomolar: '纳摩尔', micromolar: '微摩尔',
      nanosecond: '纳秒', nanoseconds: '纳秒',
      microsecond: '微秒', microseconds: '微秒',
      second: '秒', seconds: '秒',
      newton: '牛顿', newtons: '牛顿',
      micronewton: '微牛顿', micronewtons: '微牛顿',
      tesla: '特斯拉', gauss: '高斯',
    },
    convertPage: {
      h1Pattern: '{from}到{to}转换器',
      introPattern: '即时将{from}（{fromSymbol}）转换为{to}（{toSymbol}），提供精确的科学公式、对照表和详细公制换算解析。',
      formulaHeading: '换算公式',
      formulaDesc: '要将{from}（{fromSymbol}）转换为{to}（{toSymbol}），乘以 {factor}（或除以 {divisor}）。',
      shortcutText: '快捷算法：将小数点向左移动三位。',
      quickTableHeading: '快速换算对照表',
      faqHeading: '常见问题',
      faqQ1: '1 {from}等于多少{to}？',
      faqA1: '1 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ2: '1000 {from}等于多少{to}？',
      faqA2: '1000 {fromSymbol} = {toVal} {toSymbol}.',
      faqQ3: '2500 {from}等于多少{to}？',
      faqA3: '2500 {fromSymbol} = {toVal} {toSymbol}.',
      relatedHeading: '相关公制换算器',
    },
    siPrefixPage: {
      badge: '公制标准参考',
      title: '完整 24 个国际单位制 (SI) 词头速查矩阵',
      subtitle: '国际单位制（SI）定义了从 10⁻³⁰ 到 10³⁰ 跨越 60 个数量级的 24 个词头。',
      thPrefix: '词头', thSymbol: '符号', thPower: '10 的幂', thScale: '数量级名称', thMultiplier: '乘数值',
    },
    chartsPage: {
      badge: '打印版换算表',
      title: '纳微公制换算图表',
      subtitle: '适用于高频科学实验与微纳制造的高精度对照矩阵。',
      thScientific: '科学计数法', openCalc: '打开交互式计算器与公式 →',
    },
    errorPage: {
      badge: '404 错误',
      title: '坐标超出范围',
      desc: '您请求的纳米级计算或文档路由不存在，或已在 SI 公制连续体中移位。',
      returnHome: '返回首页',
      converterBtn: '纳到微转换器',
      physicsBtn: '反重力物理研究中心',
    }
  }
};

console.log('Script loaded.');
